DROP TABLE IF EXISTS messages;
CREATE TABLE IF NOT EXISTS settings
(
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  alias VARCHAR NOT NULL,
  value VARCHAR NOT NULL,
  created_time DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS users
(
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  email VARCHAR NOT NULL,
  password VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS slider
(
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  position INTEGER NOT NULL,
  src VARCHAR NOT NULL
);